### ISSUE TITLE
Feature request: better memory management for PlayerUnitEvents

### ISSUE THREAD

**Issue by YakaryBovine** [Orden4/WCSharp#1]
Hi, incredible library, thankyou. I'm leveraging PlayerUnitEvents extensively because my map has an extremely large number of units and a need for high optimization.

Usually, when I register a PlayerUnitEvent, I expect to unregister it as soon as the registering object is either disposed of or garbage collected. Currently I can't do this with PlayerUnitEvents.Unregister, because as far as I can tell that will also unregister any other registering object that registered against the same event and integer ID. I don't have a clear idea how this could be resolved. 

Happy to clarify if need be.

**Comment by Orden4** [comment]
Hm, I'm a bit confused here. I am aware that there are some issues with overlapping registrations for the same event, but I don't understand your issue?

Registrations are done either as a global trigger, or as a filter on some type id, typically unit type. There should never be a case of needing to unregister anything because of a single object (unit) being disposed of. Unregistering only makes sense if every instance of that unit type is gone from the map, though frankly I think you're better off just leaving them registered since it won't really make an impact on memory or performance to leave them there.

In fact, Lua's garbage collection works strangely in WC3, in that it does a huge sweep all at once for all players. It is not constantly cleaning memory, and if anything you'd rather avoid to trigger this sweep at all, since it'll typically cause a notable lag spike and just generally doesn't help performance in the long term. By constantly registering and unregistering events, you'd hit the memory threshold to cause a sweep earlier, which is probably not what you want.

EDIT: The one case in which unregistering does make sense, is if that would cause the backing event to be unregistered as a whole. e.g. if you only have one bit of code that listens to the `UnitTypeAttacks` or `UnitTypeIsAttacked` event, then unregistering it will cause that event to be unregistered and will improve performance. However, there is no real difference between registering this event 1 or 20 times.

I think probably what you're doing is approaching the problem from the wrong angle. e.g. say there is a unit that can cast a spell that will apply a buff on itself that makes it heal when attacking for 10 seconds. This code should probably look like this:

```CSharp
public class AttackOnHeal
{
	// We're programming this with the expectation that this is a self-cast buff that cannot overlap, so a dictionary like this is fine
	private static readonly Dictionary<unit, AttackOnHealBuff> activeBuffs = new Dictionary<unit, AttackOnHealBuff>();

	// You can just call this when the map starts. You can try and track the number of these units that are alive but this is hardly worth the effort.
	public static void Init()
	{
		// Register to my custom spell being cast
		PlayerUnitEvents.Register(PlayerUnitEvent.SpellEffect, SpellIsCast, Constants.ABILITY_MY_CUSTOM_SPELL);
	}

	private static void SpellIsCast()
	{
		var unit = GetTriggerUnit();
		// Add to the dictionary
		var buff = new AttackOnHealBuff(unit);
		activeBuffs.Add(unit, buff);
		BuffSystem.Add(buff)
		// If this is the only instance, then that means we haven't yet registered the attack event
		if (activeBuffs.Count == 1)
		{
			// Since only one unit type can cast this spell, we can filter on it
			// If multiple unit types can cast this spell, you'd just have to drop the unit type filter and make it a generic thing
			PlayerUnitEvents.Register(PlayerUnitEvent.UnitTypeAttacks, UnitAttacks, Constants.UNIT_MY_CUSTOM_UNIT);
		}
	}

	private static void UnitAttacks()
	{
		var unit = GetTriggerUnit();
		// If the unit has a buff on it, heal it
		if (activeBuffs.TryGetValue(unit, out var buff))
		{
			unit.Heal(10);
		}
	}

	// Better to make this a BoundBuff so an actual buff will show on the target, but this works as an example
	private class AttackOnHealBuff : PassiveBuff
	{
		public AttackOnHealBuff(unit caster) : base(caster, caster)
		{
			Duration = 10.0f;
		}

		// When the buff is disposed of, remove it from the dictionary
		public override void OnDispose()
		{
			// If there are no other buffs left, we can stop listening to the attack event
			if (activeBuffs.Remove(Caster) && activeBuffs.Count == 0)
			{
				PlayerUnitEvents.Unregister(PlayerUnitEvent.UnitTypeAttacks, UnitAttacks, Constants.UNIT_MY_CUSTOM_UNIT);
			}
		}
	}
}
```

You'd also have to run a UnitTypeDies event to unregister dying units of this unit type if there are effects that can explode units, since the `Caster` property would be invalid if the unit got exploded.
Thinking about it, I should probably just make the BuffSystem listen to the UnitTypeDies event so that that isn't necessary anymore.

**Comment by Orden4** [comment]
Though not really what your issue was about, I've now improved the death handling for buffs in https://github.com/Orden4/WCSharp/commit/1d6345f9b7e3cc8a211ed9288b1a5fea4152f054

**Comment by YakaryBovine** [comment]
On reflection, I think your advice here is good and you're right that just leaving them registered is the better move. Thank you.
