### ISSUE TITLE
Wiki: Update to Require NET 6

### ISSUE THREAD

**Issue by daffaabiyyu05** [Orden4/WCSharp#10]
I noticed that the wiki tutorial still uses NET 5, although the log actually mentioned NET 6 far below. This has caused me confusion when setting up

Accordingly, it is probably an ideal choice to recommend Visual Studio 2022 since Visual Studio 2019 is no longer supported for NET 6 or [with this workaround included](https://learn.microsoft.com/en-us/answers/questions/620284/how-to-target-net-6-0-with-visual-studio-2019) in the tutorial wiki.

I am referring to [this wiki page](https://github.com/Orden4/WCSharp/wiki/WCSharp-template), hope that helps!

**Comment by Orden4** [comment]
Sorry for having ignored this for a while. I've been a bit lazy to update since I just want the next version to upgrade to v3.0 using WCSharp API instead of War3Net. I've been using the new API for a while in Spectrum TD and I haven't experienced any real issues or gotten much comments in recent times, so I'll look to get them out of pre-release soon. Ideally I just make the next release use .NET 7 as well, though I'll have to see if that will work out.
