### ISSUE TITLE
PlayerUnitEvents issue

### ISSUE THREAD

**Issue by Tomos7373** [Orden4/WCSharp#11]
Hi,
I am trying to update my map to use 3.0 version and i have encountered issue with PlayerUnitEvents.
When trying to register UnitTypeEvent without unit id, it fails
For example: PlayerUnitEvents.Register(UnitTypeEvent.IsAttacked, () => Console.WriteLine("Attacked"));
after adding try catch, it is following error: (PlayerUnitEvents.EnableDebug(); does not catch this error)
"Unable to cast event filter to required type System.Int32 (Parameter 'filterObj')"

**Comment by Orden4** [comment]
EnableDebug just makes it add try/catch blocks when the entry point is WCSharp (i.e., an event managed by WCSharp goes off, then WCSharp calls your code). If the entry point is your code (i.e. an event managed by you goes off, then you call WCSharp), then there is no try/catch block, since that's your job. So EnableDebug not handling this is expected and intended.

Anyways, I've fixed this issue in v3.0.1 https://github.com/Orden4/WCSharp/commit/8509e0052d7dd4edbdd535a2ed3fb01420312b39
