### ISSUE TITLE
how to create a template for War3 1.27 version

### ISSUE THREAD

**Issue by junshangshui** [Orden4/WCSharp#12]
May I ask how to create a WCSharp-template for War3 1.27 version.

**Comment by Orden4** [comment]
Unfortunately, that isn't possible. This whole thing relies on compiling C# code into Lua code, but Lua support has only been around since 1.29 (unstable)/1.30. Any versions before then cannot be supported unless someone one day comes up with something that converts C#/Lua into JASS, but I don't really see that ever being a thing.

I'll just close this issue since this isn't something that I can help with, but feel free to ask more questions.
