### ISSUE TITLE
Cannot unregister a specific action from a custom player unit event

### ISSUE THREAD

**Issue by YakaryBovine** [Orden4/WCSharp#5]
I'm making extensive use of your PlayerUnitEvents system, and I was wondering if you could add an Unregister overload with the following signature: `public static void Unregister(string identifier, Action action)`, which would let me unregister a specific action from my custom event the same way I can do with the built-in events.

For reference I'm trying to achieve something like this:
```cs
    public override void OnAdd(player whichPlayer)
    {
      PlayerUnitEvents.Register(CustomPlayerUnitEvents.PlayerDealsDamage, OnDealDamage, GetPlayerId(whichPlayer));
    }

    public override void OnRemove(player whichPlayer)
    {
      PlayerUnitEvents.Unregister(CustomPlayerUnitEvents.PlayerDealsDamage, OnDealsDamage);
    }

    private void OnDealDamage()
    {
      //do stuff
    }
```

**Comment by Orden4** [comment]
The reason it's setup as it is is because there's no use to supplying a specific action in v2.0 of the event system. You can only register to a certain event/filterId combination once, so specifying the specific Action to remove is pointless.

You could try switching to pre-release versions of WCSharp. In v2.1, I've rewritten the PlayerUnitEvents system practically from scratch so as to better support a variety of events, make things easier to understand, and address the issue of not being able to bind multiple actions to the same event/filterId. There are no other breaking changes in v2.1.  
It's been on pre-release for a few months as I've been testing it via the development of the upcoming Spectrum TD map, but by now it's perfectly stable and it's only still in pre-release because I've been too lazy to update the wiki (but you shouldn't need that to figure out how to update, as it's fairly straight forward once you see the new Register overloads).  
It has a `Unregister(string identifier, Action action, int filterId)` method, which should meet your needs. It does still require the filterId, but I don't feel that providing a variant without really adds anything? Such a variant would mean iterating over every single event handler and removing every instance of that Action, which I'm not really sure is the desired behaviour.

I suppose I'll try to get it out of pre-release this weekend, since I'd not really be interested in addressing this in the v2.0 version anyway.

**Comment by YakaryBovine** [comment]
Brilliant, thank you so much. I'll go ahead and upgrade - that 2.1 feature sounds great and I'll happily be on a prerelease to get it.
I agree that there is no need for an Unregister that leaves out the filterId. 

I'll take this opportunity to say, once again, that WCSharp is a fantastic library and a big part of the reason I chose to use C# instead of TypeScript for my map.
